### ISSUE TITLE
自己紹介ファイル(など)をこのリポジトリに加えるまでのチュートリアルを作りたい

### ISSUE THREAD

**Issue by yucao24hours** [yochiyochirb/meetups#22]
# TODO
- [x] git clone
- [x] branch ~ checkout
- [x] add ~ commit ~ push 
- [x] send pull request
- [x] merge pull request
